Repository ArmaForces/ArmaServerManager, pull requests merged in 2021-07, with the labels that each got.

#63 Add Arma Units timeout setting to default server settings
  ArmaForces.Arma.Server/example_server.cfg
Labels: enhancement

#65 Add Dlcs to Modsets
  ArmaForces.Arma.Server.Tests/Features/Modsets/ModsetTests.cs
  ArmaForces.Arma.Server.Tests/Helpers/DlcHelpers.cs
  ArmaForces.Arma.Server.Tests/Helpers/ModHelpers.cs
  ArmaForces.Arma.Server.Tests/Helpers/ModsetHelpers.cs
  ArmaForces.Arma.Server/Features/Dlcs/Constants/DlcAppId.cs
  ArmaForces.Arma.Server/Features/Dlcs/Dlc.cs
  ArmaForces.Arma.Server/Features/Mods/IMod.cs
  ArmaForces.Arma.Server/Features/Mods/Mod.cs
  ArmaForces.Arma.Server/Features/Modsets/Modset.cs
  ArmaForces.ArmaServerManager.sln.DotSettings
  ArmaForces.ArmaServerManager/Features/Mods/ModsCache.cs
  ArmaForces.ArmaServerManager/Features/Modsets/DTOs/WebDlc.cs
  ArmaForces.ArmaServerManager/Features/Modsets/DTOs/WebModset.cs
Labels: feature

#66 Cleanup and enhancements in tests
  ArmaForces.Arma.Server.Tests/Config/ConfigReplacerTests.cs
  ArmaForces.Arma.Server.Tests/Config/ModsetConfigTests.cs
  ArmaForces.Arma.Server.Tests/Config/ServerConfigTests.cs
  ArmaForces.Arma.Server.Tests/Config/SettingsTests.cs
  ArmaForces.Arma.Server.Tests/EnumConvert.cs
  ArmaForces.Arma.Server.Tests/Extensions/EnumerableExtensionsTests.cs
  ArmaForces.Arma.Server.Tests/Features/Keys/Finder/KeysFinderUnitTests.cs
  ArmaForces.Arma.Server.Tests/Features/Modsets/ModsetTests.cs
  ArmaForces.Arma.Server.Tests/Features/Parameters/ParametersExtractorTests.cs
  ArmaForces.Arma.Server.Tests/Features/Processes/ArmaProcessTests.cs
  ArmaForces.Arma.Server.Tests/Features/Servers/DedicatedServerTests.cs
  ArmaForces.Arma.Server.Tests/Helpers/Extensions/ResultAssertionExtensions.cs
  ArmaForces.Arma.Server.Tests/Helpers/Extensions/ResultExtensions.cs
  ArmaForces.Arma.Server.Tests/Helpers/MockedFileSystemHelpers.cs
  ArmaForces.Arma.Server.Tests/Helpers/ModHelpers.cs
  ArmaForces.Arma.Server.Tests/Providers/Parameters/HeadlessParametersProviderTests.cs
  ArmaForces.Arma.Server.Tests/Providers/Parameters/ServerParametersProviderTests.cs
  ArmaForces.Arma.Server/Extensions/EnumerableExtensions.cs
  ArmaForces.Arma.Server/Extensions/ServiceCollectionExtensions.cs
  ArmaForces.Arma.Server/Features/Keys/IO/KeysCopier.cs
  ArmaForces.Arma.Server/Features/Keys/KeysPreparer.cs
  ArmaForces.Arma.Server/Features/Parameters/IProcessParameters.cs
  ArmaForces.Arma.Server/Features/Parameters/ProcessParameters.cs
  ArmaForces.Arma.Server/Features/Processes/ArmaProcessDiscoverer.cs
  ArmaForces.Arma.Server/Features/Servers/ServerBuilder.cs
  ArmaForces.Arma.Server/Features/Servers/ServerBuilderFactory.cs
  ArmaForces.Arma.Server/Providers/Configuration/IModsetConfigurationProvider.cs
  ArmaForces.Arma.Server/Providers/Configuration/ModsetConfigurationProvider.cs
  ArmaForces.Arma.Server/Providers/Parameters/HeadlessParametersProvider.cs
  ArmaForces.ArmaServerManager.Tests/Extensions/DateTimeExtensionsTests.cs
  ArmaForces.ArmaServerManager.Tests/Extensions/ModExtensionsTests.cs
  ArmaForces.ArmaServerManager.Tests/Extensions/ServiceCollectionExtensions.cs
  ArmaForces.ArmaServerManager.Tests/Extensions/ServiceCollectionExtensionsTests.cs
  ArmaForces.ArmaServerManager.Tests/Features/Hangfire/HangfireManagerTests.cs
  ArmaForces.ArmaServerManager.Tests/Features/Missions/ApiMissionsClientTests.cs
  ArmaForces.ArmaServerManager.Tests/Features/Missions/Extensions/WebMissionsCollectionExtensionsTests.cs
  ArmaForces.ArmaServerManager.Tests/Features/Mods/ModsCacheTests.cs
  ArmaForces.ArmaServerManager.Tests/Features/Mods/ModsManagerIntegrationTests.cs
  ArmaForces.ArmaServerManager.Tests/Features/Mods/ModsManagerUnitTests.cs
  ArmaForces.ArmaServerManager.Tests/Features/Modsets/ApiModsetClientTests.cs
  ArmaForces.ArmaServerManager.Tests/Features/Modsets/DTOs/WebModDeserializationTests.cs
  ArmaForces.ArmaServerManager.Tests/Features/Modsets/DTOs/WebModSourceTests.cs
  ArmaForces.ArmaServerManager.Tests/Features/Modsets/DTOs/WebModTypeTests.cs
  ArmaForces.ArmaServerManager.Tests/Features/Modsets/DTOs/WebModsetDeserializationTests.cs
  ArmaForces.ArmaServerManager.Tests/Features/Steam/Content/ContentFileVerifierTests.cs
  ArmaForces.ArmaServerManager.Tests/Features/Steam/SteamClientTests.cs
  ArmaForces.ArmaServerManager.Tests/Providers/Server/ServerProviderTests.cs
  ArmaForces.ArmaServerManager/Extensions/ServiceCollectionExtensions.cs
  ArmaForces.ArmaServerManager/Features/Mods/IModsCache.cs
  ArmaForces.ArmaServerManager/Features/Mods/IModsManager.cs
  ArmaForces.ArmaServerManager/Features/Mods/ModsCache.cs
  ArmaForces.ArmaServerManager/Features/Mods/ModsManager.cs
  ArmaForces.ArmaServerManager/Features/Steam/Content/ContentDownloader.cs
  ArmaForces.ArmaServerManager/Features/Steam/Content/DTOs/ContentItem.cs
  ArmaForces.ArmaServerManager/Features/Steam/Content/IContentDownloader.cs
  ArmaForces.ArmaServerManager/Features/Steam/SteamClient.cs
  ArmaForces.ArmaServerManager/Providers/Server/ServerProvider.cs
  ArmaForces.ArmaServerManager/Startup.cs
Labels: enhancement, ignore changelog

#67 Fix discovered dedicated server shutdown didn't remove server
  ArmaForces.Arma.Server.Tests/Features/Servers/DedicatedServerTests.cs
  ArmaForces.Arma.Server/Features/Servers/DedicatedServer.cs
Labels: Bugfix

#68 Fix server status returning stopped for restarted server
  ArmaForces.ArmaServerManager/Providers/Server/ServerProvider.cs
Labels: Bugfix
