Repository ArmaForces/ArmaServerManager, pull requests merged in 2021-01, with the labels that each got.

#35 Server start and shutdown fixes and enhancements
  ArmaForces.Arma.Server/Features/Server/ServerProcess.cs
  ArmaForces.ArmaServerManager/Extensions/RestClientExtensions.cs
  ArmaForces.ArmaServerManager/Features/Missions/ApiMissionsClient.cs
  ArmaForces.ArmaServerManager/Services/ServerStartupService.cs
  ArmaForces.ArmaServerManager/Startup.cs
Labels: Bugfix, enhancement

#36 Disable anti forgery token for Hangfire Dashboard
  ArmaForces.ArmaServerManager/Startup.cs
Labels: Bugfix

#37 Schedule updateMods job after shutdown job from mods controller
  ArmaForces.ArmaServerManager/Controller/ModsController.cs
  ArmaForces.ArmaServerManager/Features/Hangfire/HangfireManager.cs
  ArmaForces.ArmaServerManager/Features/Hangfire/Helpers/HangfireBackgroundJobClient.cs
  ArmaForces.ArmaServerManager/Features/Hangfire/Helpers/IHangfireBackgroundJobClient.cs
  ArmaForces.ArmaServerManager/Features/Hangfire/IHangfireManager.cs
Labels: enhancement

#38 Update example server configs provided with manager
  ArmaForces.Arma.Server/example_basic.cfg
  ArmaForces.Arma.Server/example_server.cfg
Labels: enhancement

#39 Update mod data in cache during mapping web modset to cache mods
  ArmaForces.ArmaServerManager/Extensions/ModExtensions.cs
  ArmaForces.ArmaServerManager/Features/Mods/ModDirectoryFinder.cs
  ArmaForces.ArmaServerManager/Features/Mods/ModsCache.cs
Labels: Bugfix

#40 Schedule startServer job after shutdown job from server controller
  ArmaForces.ArmaServerManager/Controller/ServerController.cs
Labels: enhancement

#41 Copy mods keys on server startup
  ArmaForces.Arma.Server.Tests/Features/Server/DedicatedServerTests.cs
  ArmaForces.Arma.Server/ArmaForces.Arma.Server.csproj
  ArmaForces.Arma.Server/Constants/KeysConstants.cs
  ArmaForces.Arma.Server/Features/Modsets/IModset.cs
  ArmaForces.Arma.Server/Features/Modsets/Modset.cs
  ArmaForces.Arma.Server/Features/Server/DedicatedServer.cs
  ArmaForces.Arma.Server/Providers/Keys/IKeysProvider.cs
  ArmaForces.Arma.Server/Providers/Keys/KeysProvider.cs
  ArmaForces.Arma.Server/a3.bikey
  ArmaForces.ArmaServerManager/Providers/Server/ServerProvider.cs
  ArmaForces.ArmaServerManager/Startup.cs
Labels: feature

#42 Improve logging
  ArmaForces.Arma.Server.Tests/Config/ConfigReplacerTests.cs
  ArmaForces.Arma.Server.Tests/Config/ModsetConfigTests.cs
  ArmaForces.Arma.Server/Config/ConfigFileCreator.cs
  ArmaForces.Arma.Server/Config/ConfigReplacer.cs
  ArmaForces.Arma.Server/Config/ModsetConfig.cs
  ArmaForces.Arma.Server/Features/Server/A2SInfo.cs
  ArmaForces.Arma.Server/Features/Server/ServerProcess.cs
  ArmaForces.Arma.Server/Providers/Configuration/ServerConfigurationProvider.cs
  ArmaForces.ArmaServerManager.Tests/Providers/Server/ServerProviderTests.cs
  ArmaForces.ArmaServerManager/Features/Steam/Content/ContentVerifier.cs
  ArmaForces.ArmaServerManager/Providers/Server/ServerProvider.cs
  ArmaForces.ArmaServerManager/Startup.cs
Labels: enhancement

#43 Force one job at a time
  ArmaForces.ArmaServerManager/Startup.cs
Labels: enhancement

#44 Return 202 Accepted instead of 200 Ok when scheduling jobs by API
  ArmaForces.ArmaServerManager/Controller/ModsController.cs
  ArmaForces.ArmaServerManager/Controller/ServerController.cs
Labels: enhancement
